### ISSUE TITLE
Query regarding dependency github.com/zambien/go-apigee-edge

### ISSUE THREAD

**Issue by moredhel** [zambien/terraform-provider-apigee#52]
Hi,

I am looking through your provider and see that you are maintaining a fork of the go-apigee-edge go library which you are using in your provider.

What is the purpose of doing this rather than depending directly on the upstream library?

I'm wanting to extend the underlying library to support additional services within ApiGee.

Alternatively, is there something I can do to help merge the two repos so we can depend pool our efforts.

Thanks

[0] github.com/zambien/go-apigee-edge

**Comment by zambien** [comment]
Hi @moredhel.  I'm not totally sure I understand the question.  I have a fork of go-apigee-edge because my PR to that original repo hasn't been commented on or merged in:  https://github.com/DinoChiesa/go-apigee-edge/pull/4

I haven't merged that library with this plugin because the go-apigee-edge API could be used independently.   

Maybe I'm not understanding the question though.  Could you elaborate?

Thanks!

**Comment by moredhel** [comment]
Thanks Zambien for the reply. It looks like that repository hasn't made any updates for a while. In that case I'll look into putting together a PR against this repo.

Thanks for clarifying, I would like to merge the two projects again if possible as it will reduce the overhead.
